stages:
  - test-deb

test_deb:
  stage: test-deb
  image: "example/deb-tester:latest"
  script:
    # Since the image entrypoint is the app itself, we can pass args or check help
    # Note: GitLab CI overrides the entrypoint to run the shell script
    - deb-tester --help

