stages:
  - build

variables:
  TEST_IMAGE: my-registry/deb-tester:latest

# Build the tester image
build_tester:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $TEST_IMAGE .
    # - docker push $TEST_IMAGE

